language: java
sudo: false
install:
  - rvm install 2.6.3 --rubygems 3.0.4
  - rvm use 2.6.3 --default
  - gem install jekyll
script: mvn package
after_success: mvn cobertura:cobertura coveralls:report
jdk:
  - openjdk11
