language: java
sudo: false
install:
  - rvm install 2.6.0 --rubygems 2.5.0
  - rvm use 2.6.0 --default
  - gem install jekyll
script: mvn package
after_success: mvn cobertura:cobertura coveralls:report
jdk:
  - openjdk8
  - openjdk11
